<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>ly.count.consumer</groupId>
  <artifactId>countly-consumer</artifactId>
  <version>1</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>${countly.release}</maven.compiler.release>
  </properties>

  <repositories>
    <repository>
      <id>countly</id>
      <url>${countly.repository}</url>
    </repository>
    <repository>
      <id>countly-public</id>
      <url>${countly.publicRepository}</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>ly.count.sdk</groupId>
      <artifactId>${countly.artifact}</artifactId>
      <version>${countly.version}</version>
    </dependency>
  </dependencies>

  <build>
    <sourceDirectory>${project.basedir}/../probes/${countly.artifact}</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.14.0</version>
      </plugin>
    </plugins>
  </build>
</project>
