name: Java Gradle Build and Test

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8' 

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew sdk-java:test
